version: "3"

services:
    php:
        build: ./php-fpm
        working_dir: /var/www/html
        volumes:
            - ./workspace:/var/www/html
    nginx:
        image: nginx
        working_dir: /var/www/html
        volumes:
            - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
            - ./workspace:/var/www/html
        links:
            - php
        ports:
            - "80:80"
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: dbname
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpass
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - '8081:80'
    node:
        build: ./node
        working_dir: /var/www/html
        volumes:
            - ./workspace:/var/www/html
        tty: true
    mongo:
        image: mongo:3.4
        environment:
            - MONGO_INITDB_DATABASE=mongo
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        ports:
            - "27017:27017"
    rabbit:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: mq
        volumes:
            - ./.data/rabbitmq/:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
    elk:
        image: sebp/elk
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - ./.data/elasticsearch:/var/lib/elasticsearch
            #- ./elk/elasticsearch:/etc/elasticsearch # to place elastisearch.yml configuration
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
    redis:
        image: redis:latest
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
        - .data/redis:/data